//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyLibrary.WebApp.TinyLibraryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookData", Namespace="http://schemas.datacontract.org/2004/07/TinyLibrary.Services.DataObjects")]
    [System.SerializableAttribute()]
    public partial class BookData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LendToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LendDate {
            get {
                return this.LendDateField;
            }
            set {
                if ((this.LendDateField.Equals(value) != true)) {
                    this.LendDateField = value;
                    this.RaisePropertyChanged("LendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LendTo {
            get {
                return this.LendToField;
            }
            set {
                if ((object.ReferenceEquals(this.LendToField, value) != true)) {
                    this.LendToField = value;
                    this.RaisePropertyChanged("LendTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Lent {
            get {
                return this.LentField;
            }
            set {
                if ((this.LentField.Equals(value) != true)) {
                    this.LentField = value;
                    this.RaisePropertyChanged("Lent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((this.PagesField.Equals(value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReaderData", Namespace="http://schemas.datacontract.org/2004/07/TinyLibrary.Services.DataObjects")]
    [System.SerializableAttribute()]
    public partial class ReaderData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationData", Namespace="http://schemas.datacontract.org/2004/07/TinyLibrary.Services.DataObjects")]
    [System.SerializableAttribute()]
    public partial class RegistrationData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BookGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReaderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReaderUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BookGuid {
            get {
                return this.BookGuidField;
            }
            set {
                if ((this.BookGuidField.Equals(value) != true)) {
                    this.BookGuidField = value;
                    this.RaisePropertyChanged("BookGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookISBN {
            get {
                return this.BookISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.BookISBNField, value) != true)) {
                    this.BookISBNField = value;
                    this.RaisePropertyChanged("BookISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookTitle {
            get {
                return this.BookTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTitleField, value) != true)) {
                    this.BookTitleField = value;
                    this.RaisePropertyChanged("BookTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReaderName {
            get {
                return this.ReaderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReaderNameField, value) != true)) {
                    this.ReaderNameField = value;
                    this.RaisePropertyChanged("ReaderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReaderUserName {
            get {
                return this.ReaderUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReaderUserNameField, value) != true)) {
                    this.ReaderUserNameField = value;
                    this.RaisePropertyChanged("ReaderUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusText {
            get {
                return this.StatusTextField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusTextField, value) != true)) {
                    this.StatusTextField = value;
                    this.RaisePropertyChanged("StatusText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TinyLibraryService.ITinyLibraryService")]
    public interface ITinyLibraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/SayHello", ReplyAction="http://tempuri.org/ITinyLibraryService/SayHelloResponse")]
        string SayHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/GetAllBooks", ReplyAction="http://tempuri.org/ITinyLibraryService/GetAllBooksResponse")]
        TinyLibrary.WebApp.TinyLibraryService.BookData[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/AddBook", ReplyAction="http://tempuri.org/ITinyLibraryService/AddBookResponse")]
        void AddBook(TinyLibrary.WebApp.TinyLibraryService.BookData bookData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/AddReader", ReplyAction="http://tempuri.org/ITinyLibraryService/AddReaderResponse")]
        bool AddReader(TinyLibrary.WebApp.TinyLibraryService.ReaderData readerData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/GetBookDetail", ReplyAction="http://tempuri.org/ITinyLibraryService/GetBookDetailResponse")]
        TinyLibrary.WebApp.TinyLibraryService.BookData GetBookDetail(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/GetReaderRegistrations", ReplyAction="http://tempuri.org/ITinyLibraryService/GetReaderRegistrationsResponse")]
        TinyLibrary.WebApp.TinyLibraryService.RegistrationData[] GetReaderRegistrations(string readerUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/Borrow", ReplyAction="http://tempuri.org/ITinyLibraryService/BorrowResponse")]
        void Borrow(string readerUserName, System.Guid bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITinyLibraryService/Return", ReplyAction="http://tempuri.org/ITinyLibraryService/ReturnResponse")]
        void Return(string readerUserName, System.Guid bookId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITinyLibraryServiceChannel : TinyLibrary.WebApp.TinyLibraryService.ITinyLibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TinyLibraryServiceClient : System.ServiceModel.ClientBase<TinyLibrary.WebApp.TinyLibraryService.ITinyLibraryService>, TinyLibrary.WebApp.TinyLibraryService.ITinyLibraryService {
        
        public TinyLibraryServiceClient() {
        }
        
        public TinyLibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TinyLibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyLibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TinyLibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
        
        public TinyLibrary.WebApp.TinyLibraryService.BookData[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public void AddBook(TinyLibrary.WebApp.TinyLibraryService.BookData bookData) {
            base.Channel.AddBook(bookData);
        }
        
        public bool AddReader(TinyLibrary.WebApp.TinyLibraryService.ReaderData readerData) {
            return base.Channel.AddReader(readerData);
        }
        
        public TinyLibrary.WebApp.TinyLibraryService.BookData GetBookDetail(System.Guid id) {
            return base.Channel.GetBookDetail(id);
        }
        
        public TinyLibrary.WebApp.TinyLibraryService.RegistrationData[] GetReaderRegistrations(string readerUserName) {
            return base.Channel.GetReaderRegistrations(readerUserName);
        }
        
        public void Borrow(string readerUserName, System.Guid bookId) {
            base.Channel.Borrow(readerUserName, bookId);
        }
        
        public void Return(string readerUserName, System.Guid bookId) {
            base.Channel.Return(readerUserName, bookId);
        }
    }
}
